# Generated by Django 6.0 on 2025-12-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='quiz',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
