# Generated by Django 6.0 on 2026-01-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_note_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
